i18n.registerContent('en', 'quizzes', [
    // ═══════════════════════════════════════════
    // LEVEL 1 — Beginner (includes mixed question types)
    // ═══════════════════════════════════════════

    // ─── Calculation Exercises ───
    { level: 'level1', topicIndex: 2, type: 'calculation', question: 'Calculate the cutoff frequency (in Hz) of an RC low-pass filter with R = 10kΩ and C = 100nF. Use the formula: f_c = 1 / (2πRC)', answer: 159, unit: 'Hz', tolerance: 0.05, xp: 15, explanation: 'f_c = 1 / (2π × 10,000 × 0.0000001) = 1 / (0.00628) ≈ 159 Hz. This is the frequency where the output is -3dB (70.7%) of the input.' },
    { level: 'level1', topicIndex: 7, type: 'calculation', question: 'Calculate the resistor value (in Ω) needed to limit current to 15mA for a red LED (V_f = 1.8V) from a 5V supply. Use: R = (V_supply - V_LED) / I', answer: 213, unit: 'Ω', tolerance: 0.05, xp: 15, explanation: 'R = (5V - 1.8V) / 0.015A = 3.2V / 0.015A ≈ 213Ω. In practice you would use the next standard value up: 220Ω.' },

    // ─── True/False Exercises ───
    { level: 'level1', topicIndex: 0, type: 'truefalse', question: 'In Kirchhoff\'s Voltage Law (KVL), the sum of all voltage drops around any closed loop equals zero.', answer: true, xp: 10, explanation: 'This is correct. KVL states that the total voltage around any closed circuit loop is zero — energy supplied equals energy consumed.' },
    { level: 'level1', topicIndex: 1, type: 'truefalse', question: 'Electrolytic capacitors can be connected in either polarity — they are non-polarized components.', answer: false, xp: 10, explanation: 'False! Electrolytic capacitors are polarized — connecting them backwards can cause overheating, swelling, or even explosion. Always check the polarity markings (stripe = negative).' },

    { level: 'level1', topicIndex: 0, question: "What is Ohm's Law?", options: ['V = I × R', 'V = I / R', 'V = R / I', 'V = I + R'], correct: 0, explanation: "Ohm's Law states that Voltage (V) equals Current (I) times Resistance (R).", xp: 10 },
    { level: 'level1', topicIndex: 0, question: "According to Kirchhoff's Current Law, at any node in a circuit:", options: ['Voltage in equals voltage out', 'Sum of currents entering equals sum leaving', 'Resistance is always conserved', 'Power is equally distributed'], correct: 1, explanation: "KCL states that the total current entering a junction equals the total current leaving it — charge is conserved.", xp: 10 },

    // Topic 1: Core Electronic Components
    { level: 'level1', topicIndex: 1, question: 'Which component stores electrical energy in an electric field?', options: ['Inductor', 'Capacitor', 'Resistor', 'Diode'], correct: 1, explanation: 'Capacitors store energy in an electric field between two conductive plates.', xp: 10 },
    { level: 'level1', topicIndex: 1, question: 'What does BJT stand for?', options: ['Binary Junction Transistor', 'Bipolar Junction Transistor', 'Basic Joint Transistor', 'Bilateral Junction Transistor'], correct: 1, explanation: 'BJT stands for Bipolar Junction Transistor, commonly used as switches or amplifiers.', xp: 10 },

    // Topic 2: Basic Analog Circuits
    { level: 'level1', topicIndex: 2, question: 'What is the cutoff frequency formula for a first-order RC low-pass filter?', options: ['f_c = 2πRC', 'f_c = 1 / (2πRC)', 'f_c = R / C', 'f_c = RC / 2π'], correct: 1, explanation: 'The cutoff frequency where the output drops by 3dB is f_c = 1/(2πRC).', xp: 10 },
    { level: 'level1', topicIndex: 2, question: 'What is the gain formula for a non-inverting op-amp amplifier?', options: ['Gain = R_f / R_in', 'Gain = 1 + (R_f / R_in)', 'Gain = -(R_f / R_in)', 'Gain = R_in / R_f'], correct: 1, explanation: 'A non-inverting amplifier has Gain = 1 + (R_f / R_in), providing positive output.', xp: 10 },

    // Topic 3: Digital Logic Basics
    { level: 'level1', topicIndex: 3, question: 'Which logic gate is called a "universal gate" because any logic function can be built from it?', options: ['AND', 'OR', 'NAND', 'XOR'], correct: 2, explanation: 'NAND (and NOR) gates are universal — any Boolean function can be implemented using only NAND gates.', xp: 10 },
    { level: 'level1', topicIndex: 3, question: 'What is the decimal value of binary 1011?', options: ['9', '10', '11', '13'], correct: 2, explanation: '1011 in binary = 1×8 + 0×4 + 1×2 + 1×1 = 8 + 0 + 2 + 1 = 11.', xp: 10 },

    // Topic 4: Tools & Instrumentation Basics
    { level: 'level1', topicIndex: 4, question: 'When measuring resistance with a multimeter, you must:', options: ['Apply maximum voltage', 'Power off the circuit first', 'Use AC mode', 'Connect in series'], correct: 1, explanation: 'Always power off the circuit before measuring resistance — active voltage will give wrong readings and may damage the meter.', xp: 10 },
    { level: 'level1', topicIndex: 4, question: 'An oscilloscope primarily measures:', options: ['Resistance over time', 'Current waveforms directly', 'Voltage waveforms over time', 'Power consumption'], correct: 2, explanation: 'An oscilloscope visualizes voltage signals over time. Current can be measured indirectly via a shunt resistor or current probe.', xp: 10 },

    // Topic 5: Intro to PCB Design Concepts
    { level: 'level1', topicIndex: 5, question: 'What is a "via" in PCB design?', options: ['A copper trace on the top layer', 'A plated hole connecting different copper layers', 'The edge cut of the board', 'A component footprint'], correct: 1, explanation: 'A via is a plated hole that creates an electrical connection between different copper layers of the PCB.', xp: 10 },
    { level: 'level1', topicIndex: 5, question: 'What is the purpose of solder mask on a PCB?', options: ['Increase conductivity', 'Protect copper and prevent solder bridges', 'Add mechanical strength', 'Improve heat dissipation'], correct: 1, explanation: 'Solder mask (the green/blue coating) covers copper traces to prevent accidental solder bridges and provides electrical insulation.', xp: 10 },

    // Topic 6: Beginner EDA Tool Workflow (KiCad)
    { level: 'level1', topicIndex: 6, question: 'In KiCad, what does ERC stand for?', options: ['Electronic Routing Check', 'Electrical Rule Check', 'Error Recovery Console', 'Edge Reference Constraint'], correct: 1, explanation: 'ERC (Electrical Rule Check) catches schematic errors like unconnected pins, missing power connections, and conflicting outputs.', xp: 10 },
    { level: 'level1', topicIndex: 6, question: 'What file format is the industry standard for PCB fabrication?', options: ['PDF', 'SVG', 'Gerber (RS-274X)', 'DXF'], correct: 2, explanation: 'Gerber files (RS-274X format) are the universal standard for communicating PCB designs to fabrication houses.', xp: 10 },

    // Topic 7: Beginner Projects
    { level: 'level1', topicIndex: 7, question: 'In a 555 timer astable circuit, the output produces:', options: ['A constant DC voltage', 'A continuous square wave', 'A single pulse', 'A sine wave'], correct: 1, explanation: 'In astable mode, the 555 timer generates a continuous square wave output — useful for blinking LEDs and clock signals.', xp: 10 },
    { level: 'level1', topicIndex: 7, question: 'What resistor value is needed to limit current to 20mA for an LED (Vf=2V) from a 5V supply?', options: ['100Ω', '150Ω', '220Ω', '330Ω'], correct: 1, explanation: 'R = (V_supply - V_LED) / I = (5V - 2V) / 0.02A = 150Ω.', xp: 10 },

    // Topic 8: Soldering & Assembly Skills
    { level: 'level1', topicIndex: 8, question: 'The ideal soldering iron temperature for lead-free solder (SAC305) is approximately:', options: ['200°C', '280°C', '350–370°C', '450°C'], correct: 2, explanation: 'Lead-free solder melts at ~217°C, so an iron temp of 350–370°C provides enough thermal transfer for good joints without damaging components. Too hot burns flux; too cold creates cold joints.', xp: 10 },
    { level: 'level1', topicIndex: 8, question: 'A "cold solder joint" is characterized by:', options: ['A smooth, shiny, concave fillet', 'A dull, grainy, blob-like appearance with poor wetting', 'A perfectly flat connection', 'Blue discoloration on the pad'], correct: 1, explanation: 'Cold joints occur when insufficient heat was applied — solder doesn\'t fully melt and wet the surfaces, resulting in a dull, rough, unreliable connection that may fail under vibration.', xp: 10 },

    // ═══════════════════════════════════════════
    // LEVEL 2 — Intermediate (includes mixed question types)
    // ═══════════════════════════════════════════

    // ─── L2 Calculation Exercises ───
    { level: 'level2', topicIndex: 2, type: 'calculation', question: 'An LDO converts 12V to 3.3V at 400mA. Calculate the power dissipated as heat: P = (Vin - Vout) × I', answer: 3.48, unit: 'W', tolerance: 0.05, xp: 20, explanation: 'P = (12V - 3.3V) × 0.4A = 8.7V × 0.4A = 3.48W. That\'s a lot of heat! An LDO is very inefficient here (27% efficiency). A buck converter would be ~90% efficient.' },
    { level: 'level2', topicIndex: 5, type: 'calculation', question: 'Using IPC-2152, a 1oz outer-layer trace carrying 2A with 10°C rise needs approximately what width in mil? (Answer: 40)', answer: 40, unit: 'mil', tolerance: 0.15, xp: 20, explanation: 'Per IPC-2152 charts, ~1.0mm (40 mil) width on outer layer with 1oz copper carries ~2A at 10°C temperature rise. Inner layers need ~2× wider for the same current.' },

    // ─── L2 True/False Exercises ───
    { level: 'level2', topicIndex: 4, type: 'truefalse', question: 'I2C requires external pull-up resistors because the bus uses open-drain outputs.', answer: true, xp: 15, explanation: 'Correct! I2C devices can only pull SDA/SCL lines LOW. External pull-up resistors (typically 4.7kΩ) are needed to pull lines HIGH when released. Without them, communication fails.' },
    { level: 'level2', topicIndex: 4, type: 'truefalse', question: 'SPI requires a maximum of 3 wires regardless of how many slave devices are connected.', answer: false, xp: 15, explanation: 'False! SPI needs MOSI, MISO, SCK (3 shared lines) PLUS one CS (chip select) line per slave device. With 4 slaves, you need 7 wires total.' },

    // Topic 0: Deeper Analog Electronics
    { level: 'level2', topicIndex: 0, question: 'What does Gain-Bandwidth Product (GBW) mean for an op-amp?', options: ['Gain plus bandwidth equals constant', 'Gain × Bandwidth = constant', 'Gain is independent of bandwidth', 'Bandwidth doubles when gain doubles'], correct: 1, explanation: 'GBW is constant: if you increase gain, bandwidth decreases proportionally. Example: 1MHz GBW at gain 100 → 10kHz bandwidth.', xp: 15 },
    { level: 'level2', topicIndex: 0, question: 'An instrumentation amplifier is specifically designed for:', options: ['High-power output drive', 'Amplifying low-level differential signals with high CMRR', 'Oscillator circuits', 'Digital signal buffering'], correct: 1, explanation: 'Instrumentation amps have very high CMRR (80-120dB) and high input impedance, ideal for strain gauges, load cells, and current sensing.', xp: 15 },

    // Topic 1: Intermediate Digital Electronics
    { level: 'level2', topicIndex: 1, question: 'To interface a 5V Arduino with a 3.3V ESP32 GPIO, you need:', options: ['Nothing — they are compatible', 'A voltage level shifter', 'A larger power supply', 'An additional ground wire'], correct: 1, explanation: 'ESP32 GPIOs are not 5V tolerant. A MOSFET-based level shifter (e.g., BSS138) or resistor divider is needed to avoid damage.', xp: 15 },
    { level: 'level2', topicIndex: 1, question: 'A crystal oscillator on an MCU board requires which external components?', options: ['Just the crystal alone', 'Crystal + two load capacitors to ground', 'Crystal + series resistor only', 'Crystal + inductor + capacitor'], correct: 1, explanation: 'Crystals need two load capacitors (typically 18-22pF) connected from each pin to ground to establish the correct oscillation frequency.', xp: 15 },

    // Topic 2: Power Electronics
    { level: 'level2', topicIndex: 2, question: 'What is the efficiency of an LDO regulating 5V from 12V input?', options: ['About 95%', 'About 80%', 'About 42%', 'About 66%'], correct: 2, explanation: 'LDO efficiency = V_out / V_in = 5V / 12V ≈ 42%. The remaining 58% is wasted as heat — a buck converter would be far better here.', xp: 15 },
    { level: 'level2', topicIndex: 2, question: 'In a buck (step-down) converter, the relationship V_out = V_in × D refers to:', options: ['D = diode voltage', 'D = duty cycle of the switching signal', 'D = distance between components', 'D = decoupling factor'], correct: 1, explanation: 'In a buck converter, the output voltage equals the input voltage multiplied by the PWM duty cycle (0 to 1).', xp: 15 },

    // Topic 3: Microcontroller Hardware Design
    { level: 'level2', topicIndex: 3, question: 'What is the primary purpose of decoupling capacitors near MCU power pins?', options: ['Increase voltage', 'Filter AC signals', 'Reduce power supply noise and provide local charge', 'Store energy long-term'], correct: 2, explanation: 'Decoupling caps provide a local charge reservoir, reducing high-frequency noise on power pins. Rule: 100nF per VCC/GND pair.', xp: 15 },
    { level: 'level2', topicIndex: 3, question: 'STM32 SWD debugging requires at minimum:', options: ['MOSI, MISO, SCK, GND', 'TX, RX, GND', 'SWDIO, SWCLK, GND', 'TDI, TDO, TCK, TMS, GND'], correct: 2, explanation: 'SWD (Serial Wire Debug) needs just 3 connections: SWDIO (data), SWCLK (clock), and GND. VCC is optional for target detection.', xp: 15 },

    // Topic 4: Communication Interfaces
    { level: 'level2', topicIndex: 4, question: 'CAN bus requires what termination at each end of the bus?', options: ['50Ω resistor', '120Ω resistor between CAN_H and CAN_L', '10kΩ pull-up on each line', 'No termination needed'], correct: 1, explanation: 'CAN bus requires 120Ω termination resistors at both ends of the bus to prevent signal reflections.', xp: 20 },
    { level: 'level2', topicIndex: 4, question: 'I2C pull-up resistors are needed because the bus uses:', options: ['Push-pull outputs', 'Open-drain outputs that can only pull low', 'Differential signaling', 'Tri-state buffers'], correct: 1, explanation: 'I2C uses open-drain topology — devices can only pull the line low. External pull-up resistors pull the lines high when released.', xp: 15 },

    // Topic 5: Intermediate PCB Layout
    { level: 'level2', topicIndex: 5, question: 'In a standard 4-layer PCB stackup (Sig-GND-PWR-Sig), which layer is the solid ground plane?', options: ['Layer 1 (Top)', 'Layer 2', 'Layer 3', 'Layer 4 (Bottom)'], correct: 1, explanation: 'Layer 2 is typically a solid ground plane, providing excellent return paths for signals on Layer 1 and shielding.', xp: 15 },
    { level: 'level2', topicIndex: 5, question: 'For a 2A trace at 10°C rise on the outer layer (1oz copper), the approximate trace width needed is:', options: ['0.1mm (4 mil)', '0.4mm (16 mil)', '1.0mm (40 mil)', '3.0mm (120 mil)'], correct: 2, explanation: 'Per IPC-2152, ~1.0mm (40 mil) width on outer layer with 1oz copper carries ~2A at 10°C rise.', xp: 20 },

    // Topic 6: DFM & DFA
    { level: 'level2', topicIndex: 6, question: 'What are fiducial marks on a PCB used for?', options: ['Decorative board marking', 'Pick-and-place machine vision alignment', 'Electrical testing probe points', 'Drill depth calibration'], correct: 1, explanation: 'Fiducials are copper circles that the pick-and-place machine camera uses to precisely align component placement.', xp: 15 },
    { level: 'level2', topicIndex: 6, question: 'The standard minimum trace/space for budget PCB fabs is typically:', options: ['2 mil / 2 mil', '4 mil / 4 mil', '6 mil / 6 mil', '12 mil / 12 mil'], correct: 2, explanation: '6 mil / 6 mil (0.15mm) is the standard minimum for most budget fabs like JLCPCB. Stay 20% above for reliability.', xp: 15 },

    // Topic 7: Intermediate Projects
    { level: 'level2', topicIndex: 7, question: 'What is the purpose of a shunt resistor in motor control?', options: ['Voltage regulation', 'Current sensing', 'Speed control', 'Direction switching'], correct: 1, explanation: 'A shunt resistor in series with the motor allows measuring current by measuring voltage across it (V=IR).', xp: 15 },
    { level: 'level2', topicIndex: 7, question: 'What does LDO stand for in voltage regulators?', options: ['Low Dropout', 'Linear Direct Output', 'Load Distribution Output', 'Low Distortion Oscillator'], correct: 0, explanation: 'LDO (Low Dropout) regulators can operate with small voltage difference between input and output.', xp: 15 },

    // ═══════════════════════════════════════════
    // LEVEL 3 — Advanced (includes mixed question types)
    // ═══════════════════════════════════════════

    // ─── L3 Calculation Exercises ───
    { level: 'level3', topicIndex: 2, type: 'calculation', question: 'Calculate the PDN target impedance: allowed ripple = 50mV, transient current = 2A. Z_target = ΔV / ΔI', answer: 25, unit: 'mΩ', tolerance: 0.05, xp: 25, explanation: 'Z_target = 50mV / 2A = 25mΩ. The power distribution network impedance must stay below 25mΩ across all frequencies to keep ripple within spec.' },
    { level: 'level3', topicIndex: 9, type: 'calculation', question: 'Calculate the quarter-wave antenna length (in mm) for 2.4 GHz in FR-4 (velocity factor ≈ 0.5). Use: λ/4 = (c × VF) / (4 × f)', answer: 15.6, unit: 'mm', tolerance: 0.10, xp: 25, explanation: 'λ = (3×10⁸ × 0.5) / 2.4×10⁹ = 62.5mm. Quarter-wave = 62.5/4 ≈ 15.6mm. Note: the actual ~31mm commonly cited uses a velocity factor closer to 1.0 for the radiating element, but in substrate it\'s shorter.' },

    // ─── L3 True/False Exercises ───
    { level: 'level3', topicIndex: 5, type: 'truefalse', question: 'Spread-spectrum clocking eliminates EMC emissions — it removes the harmonics entirely.', answer: false, xp: 20, explanation: 'False! Spread-spectrum doesn\'t eliminate emissions — it spreads the energy over a wider frequency band, reducing the PEAK amplitude at any single frequency. Total radiated power is the same, but the peak drops by 5-10 dB.' },
    { level: 'level3', topicIndex: 7, type: 'truefalse', question: 'During board bring-up, you should power on with current limiting set to the expected maximum before verifying anything.', answer: false, xp: 20, explanation: 'False! Always start with a LOW current limit (e.g., 100mA) and verify power rails with no shorts first. Then gradually increase to the expected operating current. Full current on first power-up risks damaging components if there\'s a short.' },

    // Topic 0: Advanced Analog & Mixed-Signal
    { level: 'level3', topicIndex: 0, question: 'Kelvin sensing on a shunt resistor means:', options: ['Using 4 connections instead of 2', 'Routing sense traces from shunt pad edges to avoid trace resistance errors', 'Measuring in Kelvin temperature units', 'Using a Kelvin-rated resistor'], correct: 1, explanation: 'Kelvin sensing routes separate sense traces from the shunt pad edges directly to the amplifier, avoiding voltage drop errors from power trace resistance.', xp: 25 },
    { level: 'level3', topicIndex: 0, question: 'In a mixed-signal PCB, the analog and digital ground planes should:', options: ['Be completely separate with no connection', 'Be connected at a single point (star ground)', 'Be on different boards entirely', 'Be interleaved for best coupling'], correct: 1, explanation: 'A single-point junction between AGND and DGND prevents digital return currents from flowing through the analog section, minimizing noise coupling.', xp: 25 },

    // Topic 1: Signal Integrity
    { level: 'level3', topicIndex: 1, question: 'A trace should be treated as a transmission line when its length exceeds:', options: ['1mm', 'λ/10 of the signal edge rate', 'Half the board width', '100mm always'], correct: 1, explanation: 'When trace length > λ/10 (where λ is based on rise time, not frequency), reflections become significant. For 1ns rise time in FR-4: ~15mm.', xp: 25 },
    { level: 'level3', topicIndex: 1, question: 'The "3W rule" for reducing crosstalk means:', options: ['Use 3 wires for every signal', 'Space parallel traces at 3× the trace width', 'Maximum 3 wires per via', 'Route signals on every 3rd layer'], correct: 1, explanation: 'The 3W rule keeps center-to-center spacing of parallel traces at least 3× the trace width, reducing capacitive and inductive coupling.', xp: 25 },

    // Topic 2: Power Integrity
    { level: 'level3', topicIndex: 2, question: 'PDN target impedance is calculated as:', options: ['Z = V_supply / I_max', 'Z = ΔV_allowed / ΔI_transient', 'Z = R_trace + R_via', 'Z = 50Ω always'], correct: 1, explanation: 'PDN target impedance Z_target = ΔV/ΔI. For 10mV ripple with 1A transient: Z_target = 10mΩ across all frequencies.', xp: 25 },
    { level: 'level3', topicIndex: 2, question: 'Why use multiple capacitor values (e.g., 100µF + 10µF + 100nF) for decoupling?', options: ['Cheaper in bulk', 'Each covers a different frequency range for low impedance', 'More capacitors look more professional', 'Redundancy in case one fails'], correct: 1, explanation: 'Each capacitor has a self-resonant frequency (SRF). Bulk caps handle low-frequency, MLCCs handle mid, small ceramics handle high-frequency — together they provide low PDN impedance across all frequencies.', xp: 25 },

    // Topic 3: FPGA & SoC Hardware Design
    { level: 'level3', topicIndex: 3, question: 'In FPGA design, VCCINT refers to:', options: ['The external interface voltage', 'The core logic supply voltage (lowest, most critical)', 'The programming voltage', 'The I/O bank voltage'], correct: 1, explanation: 'VCCINT is the core (internal) supply, typically 1.0-1.2V. It powers all internal logic and has the tightest noise tolerance.', xp: 25 },
    { level: 'level3', topicIndex: 3, question: 'DDR memory address/command bus uses what routing topology?', options: ['Star topology', 'Fly-by (daisy-chain) topology', 'Point-to-point only', 'Ring topology'], correct: 1, explanation: 'Fly-by topology daisy-chains the address/command bus through each DRAM chip with a single termination at the end. Write leveling compensates for propagation delay differences.', xp: 30 },

    // Topic 4: Advanced PCB Stackups
    { level: 'level3', topicIndex: 4, question: 'Standard FR-4 has a dielectric constant (Dk) of approximately:', options: ['1.0', '2.2', '4.0–4.8', '10.0'], correct: 2, explanation: 'Standard FR-4 has Dk ≈ 4.0–4.8. This affects trace impedance and signal propagation speed. Higher-frequency designs may need lower-loss materials.', xp: 25 },
    { level: 'level3', topicIndex: 4, question: 'A microvia in HDI PCB design is:', options: ['A very small through-hole via', 'A laser-drilled blind via spanning only 1 layer', 'A via filled with copper', 'Any via under 0.5mm'], correct: 1, explanation: 'Microvias are laser-drilled (≤0.1mm), span only 1 layer, and enable via-in-pad for fine-pitch BGA fan-out.', xp: 25 },

    // Topic 5: EMC/EMI Design
    { level: 'level3', topicIndex: 5, question: 'A common-mode choke filters noise by:', options: ['Blocking all frequencies equally', 'Presenting high impedance to common-mode current while passing differential signals', 'Shorting noise to ground', 'Reflecting noise back to source'], correct: 1, explanation: 'A common-mode choke has high impedance for same-direction currents (noise) but very low impedance for opposite-direction currents (signal).', xp: 25 },
    { level: 'level3', topicIndex: 5, question: 'Spread-spectrum clocking reduces EMC emissions by:', options: ['Lowering the clock frequency', 'Spreading energy over a range of frequencies to reduce peak amplitude', 'Eliminating the clock entirely', 'Adding a filter to the output'], correct: 1, explanation: 'Spread-spectrum clocking modulates the frequency slightly, spreading the spectral energy over a wider band and reducing the peak emission at any single frequency.', xp: 25 },

    // Topic 6: IPC Standards
    { level: 'level3', topicIndex: 6, question: 'IPC-2152 is used to determine:', options: ['Solder paste stencil dimensions', 'Safe trace width for a given current and temperature rise', 'Component footprint land patterns', 'Board edge clearance'], correct: 1, explanation: 'IPC-2152 provides charts and data for calculating minimum trace width based on current, copper weight, and acceptable temperature rise.', xp: 25 },
    { level: 'level3', topicIndex: 6, question: 'IPC-7351 defines three density levels (A, B, C) for land patterns. Level B is:', options: ['Maximum — for easiest rework', 'Nominal — the most common choice', 'Minimum — for dense boards', 'Zero — no pads'], correct: 1, explanation: 'Level A = maximum (easy rework), Level B = nominal (standard), Level C = minimum (high-density). Most designs use Level B.', xp: 25 },

    // Topic 7: Testing, Bring-Up, and Debugging
    { level: 'level3', topicIndex: 7, question: 'The first step in board bring-up should be:', options: ['Flash firmware immediately', 'Connect all peripherals and test simultaneously', 'Visual inspection for solder defects', 'Power on at full voltage and current'], correct: 2, explanation: 'Always start with visual inspection — look for solder bridges, missing parts, and wrong orientation using a magnifier before applying any power.', xp: 25 },
    { level: 'level3', topicIndex: 7, question: 'Boundary scan (JTAG BSDL) in DFT is used to:', options: ['Program flash memory only', 'Test board connectivity by driving I/Os from JTAG without firmware', 'Measure power consumption', 'Check solder joint quality'], correct: 1, explanation: 'Boundary scan uses JTAG to toggle and read I/O pins, verifying correct PCB connectivity without needing working firmware. Essential for production test.', xp: 25 },

    // Topic 8: Advanced Projects
    { level: 'level3', topicIndex: 8, question: 'When designing a 3-phase BLDC motor power stage, the "hot loop" refers to:', options: ['The motor windings', 'The high dI/dt path from DC bus through FETs and back through the bus cap', 'The thermal connection to the heatsink', 'The PCB edge copper pour'], correct: 1, explanation: 'The hot loop (DC bus cap → high-side FET → load → low-side FET → cap) carries fast-switching current. Minimize its area to reduce voltage spikes and EMI.', xp: 30 },
    { level: 'level3', topicIndex: 8, question: 'A complete mobile robot mainboard bring-up should begin with:', options: ['Testing all motors at full speed', 'Power rail verification with current-limited supply, then clock, then MCU boot, then peripherals one by one', 'Connecting all sensors and reading data immediately', 'Running the full application firmware'], correct: 1, explanation: 'Staged bring-up prevents cascading failures. Verify power → clock → MCU → peripherals → motor stage sequentially, always with current-limited supply first.', xp: 30 },

    // Topic 9: Antenna & Wireless Design Basics
    { level: 'level3', topicIndex: 9, question: 'A PCB trace antenna for 2.4 GHz Wi-Fi should have a length of approximately:', options: ['λ/4 ≈ 31mm in FR-4', 'λ = 125mm', 'Any length works', '10mm always'], correct: 0, explanation: 'At 2.4 GHz in FR-4 (velocity factor ~0.5), λ ≈ 62mm, so a quarter-wave antenna is ~31mm. Exact length depends on substrate and trace geometry.', xp: 25 },
    { level: 'level3', topicIndex: 9, question: 'The ground plane under a PCB antenna should be:', options: ['Solid copper for maximum shielding', 'Removed (keep-out zone) in the antenna region to allow radiation', 'Connected to VCC for power', 'Perforated with many holes'], correct: 1, explanation: 'A ground plane under the antenna blocks radiation. The antenna area must have a copper keep-out zone on all layers. The ground plane edge becomes the antenna ground reference.', xp: 25 },

    // ═══════════════════════════════════════════
    // LEVEL 4 — Expert (includes mixed question types)
    // ═══════════════════════════════════════════

    // ─── L4 Calculation Exercises ───
    { level: 'level4', topicIndex: 2, type: 'calculation', question: 'Calculate the bootstrap capacitor value for a 100kHz half-bridge gate driver. Q_gate = 50nC, leakage = 100µA. C_boot ≥ 10 × Q_gate / V_drive. With V_drive = 12V:', answer: 42, unit: 'nF', tolerance: 0.10, xp: 30, explanation: 'C_boot ≥ 10 × 50nC / 12V = 41.7nF ≈ 42nF. Use the next standard value up: 100nF (0.1µF) for margin. This ensures the bootstrap supply doesn\'t droop during gate drive.' },
    { level: 'level4', topicIndex: 1, type: 'calculation', question: 'An eye diagram shows eye height of 300mV and eye width of 80ps at 5 Gbps (200ps UI). Calculate the eye opening ratio (eye width / UI) as a percentage:', answer: 40, unit: '%', tolerance: 0.05, xp: 35, explanation: 'Eye opening ratio = 80ps / 200ps = 0.40 = 40%. A ratio below 30% is marginal; >50% is comfortable. This channel may need pre-emphasis or equalization.' },

    // ─── L4 True/False Exercises ───
    { level: 'level4', topicIndex: 4, type: 'truefalse', question: 'NRND (Not Recommended for New Designs) means the component is immediately unavailable and must be replaced now.', answer: false, xp: 25, explanation: 'False! NRND means the manufacturer plans to discontinue but the part is STILL AVAILABLE for ordering. You should select alternatives for NEW designs, but existing production can continue until EOL (End of Life) is announced.' },
    { level: 'level4', topicIndex: 3, type: 'truefalse', question: 'An E-stop (emergency stop) for a robot should always be implemented in firmware for maximum flexibility.', answer: false, xp: 25, explanation: 'False! E-stop MUST be hardware-level (relay or MOSFET cutting motor power) independent of firmware. If firmware crashes, a software-only E-stop is useless. Hardware E-stop ensures safety even during total system failure.' },

    // Topic 0: Specialization Tracks
    { level: 'level4', topicIndex: 0, question: 'In DDR4, "write leveling" compensates for:', options: ['Voltage variations between DRAM chips', 'Propagation delay differences in fly-by clock topology', 'Temperature drift in memory', 'Manufacturing variation in capacitors'], correct: 1, explanation: "Write leveling calibrates the timing of each DRAM's data strobe relative to the clock, compensating for different fly-by propagation delays.", xp: 30 },
    { level: 'level4', topicIndex: 0, question: 'Field Oriented Control (FOC) for BLDC motors requires:', options: ['Only a single Hall sensor', 'Precise phase current measurement and coordinate transforms', 'A 555 timer for commutation', 'DC voltage only, no PWM'], correct: 1, explanation: 'FOC measures phase currents (via shunt resistors or Hall sensors), transforms them to a rotating reference frame (Clarke/Park transforms), and controls torque and flux independently.', xp: 30 },

    // Topic 1: Advanced SI/PI Simulation
    { level: 'level4', topicIndex: 1, question: 'In an eye diagram, "eye height" indicates:', options: ['The physical height of the trace', 'Voltage noise margin for reliable data recovery', 'The number of signal transitions', 'Clock jitter amount'], correct: 1, explanation: "Eye height is the vertical opening — it represents the voltage margin between logic levels. Must exceed the receiver's sensitivity threshold.", xp: 30 },
    { level: 'level4', topicIndex: 1, question: 'S11 (return loss) in S-parameter analysis represents:', options: ['Signal insertion loss through the channel', 'How much energy is reflected back due to impedance mismatch', 'Crosstalk between adjacent lines', 'Power supply noise'], correct: 1, explanation: 'S11 measures reflected energy. Low S11 (e.g., -20dB = 1% reflected) means good impedance matching; high S11 means significant mismatch.', xp: 35 },

    // Topic 2: Advanced Motor & Power Electronics
    { level: 'level4', topicIndex: 2, question: 'Bootstrap gate drive for a high-side MOSFET works by:', options: ['Using a separate isolated power supply', 'Charging a capacitor when the low-side FET is on, then using that charge to drive the high-side gate', 'Connecting gate directly to VCC', 'Using an optocoupler'], correct: 1, explanation: 'When low-side is on, the bootstrap cap charges through a diode. When high-side needs to turn on, this stored energy drives the gate above the floating source voltage.', xp: 30 },
    { level: 'level4', topicIndex: 2, question: 'A "Kelvin source connection" in gate drive design means:', options: ['Connecting the source pin to ground through a Kelvin resistor', 'Using a separate return path for gate drive ground, isolated from the power return', 'Measuring source voltage in Kelvin units', 'Using 4-terminal sense on the power MOSFET'], correct: 1, explanation: 'Kelvin source separates the gate driver return from the high dI/dt power return path, preventing voltage spikes on the power ground from affecting gate drive timing.', xp: 35 },

    // Topic 3: Complex System-Level Design
    { level: 'level4', topicIndex: 3, question: 'A power tree diagram should be created:', options: ['After PCB layout is complete', 'Before schematic work begins', 'Only for battery-powered systems', 'During firmware development'], correct: 1, explanation: 'The power tree maps every voltage rail, its source, loads, sequencing, and current budget. It must be designed before schematic capture to avoid architectural mistakes.', xp: 30 },
    { level: 'level4', topicIndex: 3, question: 'An E-stop (emergency stop) for a robot should be implemented as:', options: ['Software interrupt only', 'Hardware-level relay/MOSFET that cuts motor power regardless of firmware state', 'A reset button for the MCU', 'An over-the-air command'], correct: 1, explanation: 'E-stop must be firmware-independent — a hardware relay or MOSFET that physically disconnects motor power when triggered, ensuring safety even during firmware crashes.', xp: 30 },

    // Topic 4: Manufacturing & Supply Chain
    { level: 'level4', topicIndex: 4, question: 'Via-in-pad for SMD components requires the via to be:', options: ['Left open (standard via)', 'Filled and plated over to prevent solder wicking', 'Tented with solder mask', 'Drilled larger than normal'], correct: 1, explanation: 'Open vias under SMD pads cause solder to wick through during reflow, creating unreliable joints. Filled+plated vias provide a flat solderable surface.', xp: 30 },
    { level: 'level4', topicIndex: 4, question: '"NRND" status on a component datasheet means:', options: ['Not Rated for New Designs — still available but will be discontinued', 'New Reference Number Designation', 'Normal Rated for Normal Distribution', 'Not Returned, No Defects'], correct: 0, explanation: 'NRND (Not Recommended for New Designs) signals the manufacturer plans to discontinue the part. Select an alternative for new designs to avoid future supply issues.', xp: 30 },

    // Topic 5: Leadership & Architecture
    { level: 'level4', topicIndex: 5, question: 'A Hardware Requirements Specification (HRS) should include:', options: ['Only the schematic', 'Power budget, interface list, environment specs, reliability targets, cost targets', 'Just the BOM', 'Marketing materials'], correct: 1, explanation: 'The HRS is the single source of truth defining all hardware requirements — power, interfaces, environmental operating conditions, reliability, and cost — before design begins.', xp: 30 },
    { level: 'level4', topicIndex: 5, question: 'When communicating risk to management, the most effective framing is:', options: ['Technical jargon with exact specifications', 'Cost/risk language: "removing TVS saves $0.15/unit but creates $50k recall risk"', 'Telling them to trust the engineer', 'Hiding the risk to avoid delay'], correct: 1, explanation: 'Non-technical stakeholders respond best to decisions framed as cost vs. risk tradeoffs. This enables informed business decisions.', xp: 30 },

    // Topic 6: Flagship Projects
    { level: 'level4', topicIndex: 6, question: 'In NPI (New Product Introduction), a first-article inspection verifies:', options: ['Only the firmware functions correctly', 'That the first assembled boards match design intent — dimensions, placement, solder quality', 'That the box packaging is correct', 'Only the component cost is correct'], correct: 1, explanation: 'First-article inspection catches manufacturing setup issues before full production. Check all dimensions, component placement, solder joints, and electrical test results.', xp: 30 },
    { level: 'level4', topicIndex: 6, question: 'For open-source hardware reproducibility, the most critical practice is:', options: ['Using only through-hole components', 'Providing complete design files, BOM with specific part numbers, and assembly instructions', 'Publishing only the schematic PDF', 'Using the cheapest possible components'], correct: 1, explanation: 'Reproducibility requires: full source files (KiCad/Altium), BOM with MPN and alternates, assembly drawings, firmware source, and tested build instructions.', xp: 30 }
]);
